"""Nome descritivo da sua migração

Revision ID: 14a574410912
Revises: 46b0c57ff045
Create Date: 2025-05-23 15:08:34.470661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a574410912'
down_revision: Union[str, None] = '46b0c57ff045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
