"""Create clients, products, orders and related tables

Revision ID: 46b0c57ff045
Revises: debfa9c640de
Create Date: 2025-05-22 18:30:06.025804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b0c57ff045'
down_revision: Union[str, None] = 'debfa9c640de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
