"""Add hashed_password to clients table

Revision ID: 5d43c95bd20e
Revises: c98e6b7cca68
Create Date: 2025-05-23 15:20:57.503559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d43c95bd20e'
down_revision: Union[str, None] = 'c98e6b7cca68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
