"""Mensagem descritiva da sua migração

Revision ID: 6d76b82987cf
Revises: 5d43c95bd20e
Create Date: 2025-05-24 14:50:26.791333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d76b82987cf'
down_revision: Union[str, None] = '5d43c95bd20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
