"""Altera lazy loading de Purchase.items para select

Revision ID: 854f32a87698
Revises: b06f36a52fcf
Create Date: 2025-05-24 16:27:56.315723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854f32a87698'
down_revision: Union[str, None] = 'b06f36a52fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
