"""Add hashed_password to clients table

Revision ID: c98e6b7cca68
Revises: 14a574410912
Create Date: 2025-05-23 15:13:16.069673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98e6b7cca68'
down_revision: Union[str, None] = '14a574410912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'hashed_password')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
